# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1300, 700)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/form.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 250, 271, 301))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 261))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.acc_y_Label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.acc_y_Label.setFont(font)
        self.acc_y_Label.setText(_fromUtf8(""))
        self.acc_y_Label.setObjectName(_fromUtf8("acc_y_Label"))
        self.gridLayout.addWidget(self.acc_y_Label, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.acc_x_Label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.acc_x_Label.setFont(font)
        self.acc_x_Label.setText(_fromUtf8(""))
        self.acc_x_Label.setObjectName(_fromUtf8("acc_x_Label"))
        self.gridLayout.addWidget(self.acc_x_Label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.acc_z_Label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.acc_z_Label.setFont(font)
        self.acc_z_Label.setText(_fromUtf8(""))
        self.acc_z_Label.setObjectName(_fromUtf8("acc_z_Label"))
        self.gridLayout.addWidget(self.acc_z_Label, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.gyo_x_Label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.gyo_x_Label.setFont(font)
        self.gyo_x_Label.setText(_fromUtf8(""))
        self.gyo_x_Label.setObjectName(_fromUtf8("gyo_x_Label"))
        self.gridLayout.addWidget(self.gyo_x_Label, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.gyo_z_Label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.gyo_z_Label.setFont(font)
        self.gyo_z_Label.setText(_fromUtf8(""))
        self.gyo_z_Label.setObjectName(_fromUtf8("gyo_z_Label"))
        self.gridLayout.addWidget(self.gyo_z_Label, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.acc_scale_Label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.acc_scale_Label.setFont(font)
        self.acc_scale_Label.setText(_fromUtf8(""))
        self.acc_scale_Label.setObjectName(_fromUtf8("acc_scale_Label"))
        self.gridLayout.addWidget(self.acc_scale_Label, 7, 1, 1, 1)
        self.gyo_y_Label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.gyo_y_Label.setFont(font)
        self.gyo_y_Label.setText(_fromUtf8(""))
        self.gyo_y_Label.setObjectName(_fromUtf8("gyo_y_Label"))
        self.gridLayout.addWidget(self.gyo_y_Label, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.gyo_scale_Label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.gyo_scale_Label.setFont(font)
        self.gyo_scale_Label.setText(_fromUtf8(""))
        self.gyo_scale_Label.setObjectName(_fromUtf8("gyo_scale_Label"))
        self.gridLayout.addWidget(self.gyo_scale_Label, 8, 1, 1, 1)
        self.acc_scale_up_Button = QtGui.QPushButton(self.groupBox)
        self.acc_scale_up_Button.setGeometry(QtCore.QRect(220, 220, 21, 23))
        self.acc_scale_up_Button.setObjectName(_fromUtf8("acc_scale_up_Button"))
        self.acc_scale_down_Button = QtGui.QPushButton(self.groupBox)
        self.acc_scale_down_Button.setGeometry(QtCore.QRect(240, 220, 21, 23))
        self.acc_scale_down_Button.setObjectName(_fromUtf8("acc_scale_down_Button"))
        self.gyo_scale_up_Button = QtGui.QPushButton(self.groupBox)
        self.gyo_scale_up_Button.setGeometry(QtCore.QRect(220, 250, 21, 23))
        self.gyo_scale_up_Button.setObjectName(_fromUtf8("gyo_scale_up_Button"))
        self.gyo_scale_down_Button = QtGui.QPushButton(self.groupBox)
        self.gyo_scale_down_Button.setGeometry(QtCore.QRect(240, 250, 21, 23))
        self.gyo_scale_down_Button.setObjectName(_fromUtf8("gyo_scale_down_Button"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 180, 271, 71))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 236, 41))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_3.setContentsMargins(10, 11, 11, 11)
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.canvas_pause_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.canvas_pause_pushButton.setMinimumSize(QtCore.QSize(110, 28))
        self.canvas_pause_pushButton.setMaximumSize(QtCore.QSize(110, 28))
        self.canvas_pause_pushButton.setObjectName(_fromUtf8("canvas_pause_pushButton"))
        self.gridLayout_3.addWidget(self.canvas_pause_pushButton, 0, 1, 1, 1)
        self.canvas_start_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.canvas_start_pushButton.setMinimumSize(QtCore.QSize(110, 28))
        self.canvas_start_pushButton.setMaximumSize(QtCore.QSize(110, 28))
        self.canvas_start_pushButton.setObjectName(_fromUtf8("canvas_start_pushButton"))
        self.gridLayout_3.addWidget(self.canvas_start_pushButton, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(290, 0, 1301, 641))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.acc_groupBox = QtGui.QGroupBox(self.tab_1)
        self.acc_groupBox.setGeometry(QtCore.QRect(0, 0, 1011, 311))
        self.acc_groupBox.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.acc_groupBox.setAutoFillBackground(True)
        self.acc_groupBox.setObjectName(_fromUtf8("acc_groupBox"))
        self.gyo_groupBox = QtGui.QGroupBox(self.tab_1)
        self.gyo_groupBox.setGeometry(QtCore.QRect(0, 310, 1011, 311))
        self.gyo_groupBox.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.gyo_groupBox.setAutoFillBackground(True)
        self.gyo_groupBox.setObjectName(_fromUtf8("gyo_groupBox"))
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1011, 621))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 141, 151))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 23, 121, 110))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setMargin(11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.acc_fchoice_lineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.acc_fchoice_lineEdit.setObjectName(_fromUtf8("acc_fchoice_lineEdit"))
        self.gridLayout_5.addWidget(self.acc_fchoice_lineEdit, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.acc_dlpf_cfg_lineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.acc_dlpf_cfg_lineEdit.setObjectName(_fromUtf8("acc_dlpf_cfg_lineEdit"))
        self.gridLayout_5.addWidget(self.acc_dlpf_cfg_lineEdit, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.acc_fs_sel_lineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.acc_fs_sel_lineEdit.setObjectName(_fromUtf8("acc_fs_sel_lineEdit"))
        self.gridLayout_5.addWidget(self.acc_fs_sel_lineEdit, 2, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 3, 0, 1, 1)
        self.acc_bw_label = QtGui.QLabel(self.layoutWidget2)
        self.acc_bw_label.setObjectName(_fromUtf8("acc_bw_label"))
        self.gridLayout_5.addWidget(self.acc_bw_label, 3, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 4, 0, 1, 1)
        self.acc_scale_label = QtGui.QLabel(self.layoutWidget2)
        self.acc_scale_label.setObjectName(_fromUtf8("acc_scale_label"))
        self.gridLayout_5.addWidget(self.acc_scale_label, 4, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.frame)
        self.groupBox_5.setGeometry(QtCore.QRect(140, 0, 141, 151))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 23, 121, 110))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_6.setMargin(11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_12 = QtGui.QLabel(self.layoutWidget3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 0, 0, 1, 1)
        self.gyo_fchoice_lineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.gyo_fchoice_lineEdit.setObjectName(_fromUtf8("gyo_fchoice_lineEdit"))
        self.gridLayout_6.addWidget(self.gyo_fchoice_lineEdit, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 1, 0, 1, 1)
        self.gyo_dlpf_cfg_lineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.gyo_dlpf_cfg_lineEdit.setObjectName(_fromUtf8("gyo_dlpf_cfg_lineEdit"))
        self.gridLayout_6.addWidget(self.gyo_dlpf_cfg_lineEdit, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 2, 0, 1, 1)
        self.gyo_fs_sel_lineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.gyo_fs_sel_lineEdit.setObjectName(_fromUtf8("gyo_fs_sel_lineEdit"))
        self.gridLayout_6.addWidget(self.gyo_fs_sel_lineEdit, 2, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 3, 0, 1, 1)
        self.gyo_bw_label = QtGui.QLabel(self.layoutWidget3)
        self.gyo_bw_label.setObjectName(_fromUtf8("gyo_bw_label"))
        self.gridLayout_6.addWidget(self.gyo_bw_label, 3, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_6.addWidget(self.label_30, 4, 0, 1, 1)
        self.gyo_scale_label = QtGui.QLabel(self.layoutWidget3)
        self.gyo_scale_label.setObjectName(_fromUtf8("gyo_scale_label"))
        self.gridLayout_6.addWidget(self.gyo_scale_label, 4, 1, 1, 1)
        self.read_config_pushButton = QtGui.QPushButton(self.frame)
        self.read_config_pushButton.setGeometry(QtCore.QRect(300, 40, 75, 23))
        self.read_config_pushButton.setObjectName(_fromUtf8("read_config_pushButton"))
        self.write_config_pushButton = QtGui.QPushButton(self.frame)
        self.write_config_pushButton.setGeometry(QtCore.QRect(300, 70, 75, 23))
        self.write_config_pushButton.setObjectName(_fromUtf8("write_config_pushButton"))
        self.groupBox_6 = QtGui.QGroupBox(self.frame)
        self.groupBox_6.setGeometry(QtCore.QRect(350, 160, 341, 451))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox_6)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 321, 331))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(20, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(90, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(90, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(90, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(90, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.groupBox_8 = QtGui.QGroupBox(self.frame)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 160, 341, 441))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.tableWidget_3 = QtGui.QTableWidget(self.groupBox_8)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 100, 321, 331))
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(8, 2, item)
        self.label_15 = QtGui.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(80, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(80, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_8)
        self.label_18.setGeometry(QtCore.QRect(80, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(80, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.frame_4 = QtGui.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1011, 621))
        self.frame_4.setAutoFillBackground(True)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.status_label = QtGui.QLabel(self.frame_4)
        self.status_label.setGeometry(QtCore.QRect(360, 130, 261, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("黑体"))
        font.setPointSize(48)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.recordButton = QtGui.QPushButton(self.centralWidget)
        self.recordButton.setGeometry(QtCore.QRect(160, 610, 111, 31))
        self.recordButton.setObjectName(_fromUtf8("recordButton"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 550, 271, 61))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(22, 10, 231, 41))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setMargin(11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.x_legend_label = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.x_legend_label.setFont(font)
        self.x_legend_label.setMouseTracking(False)
        self.x_legend_label.setWordWrap(False)
        self.x_legend_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.x_legend_label.setObjectName(_fromUtf8("x_legend_label"))
        self.gridLayout_4.addWidget(self.x_legend_label, 0, 0, 1, 1)
        self.y_legend_label = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.y_legend_label.setFont(font)
        self.y_legend_label.setMouseTracking(False)
        self.y_legend_label.setWordWrap(False)
        self.y_legend_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.y_legend_label.setObjectName(_fromUtf8("y_legend_label"))
        self.gridLayout_4.addWidget(self.y_legend_label, 0, 1, 1, 1)
        self.z_legend_label = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.z_legend_label.setFont(font)
        self.z_legend_label.setMouseTracking(False)
        self.z_legend_label.setWordWrap(False)
        self.z_legend_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.z_legend_label.setObjectName(_fromUtf8("z_legend_label"))
        self.gridLayout_4.addWidget(self.z_legend_label, 0, 2, 1, 1)
        self.single_radioButton = QtGui.QRadioButton(self.centralWidget)
        self.single_radioButton.setGeometry(QtCore.QRect(20, 620, 89, 16))
        self.single_radioButton.setChecked(True)
        self.single_radioButton.setObjectName(_fromUtf8("single_radioButton"))
        self.sequence_radioButton = QtGui.QRadioButton(self.centralWidget)
        self.sequence_radioButton.setGeometry(QtCore.QRect(80, 620, 89, 16))
        self.sequence_radioButton.setObjectName(_fromUtf8("sequence_radioButton"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 0, 271, 171))
        self.tabWidget_2.setAutoFillBackground(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.frame_2 = QtGui.QFrame(self.tab_11)
        self.frame_2.setGeometry(QtCore.QRect(-10, 0, 281, 161))
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.layoutWidget5 = QtGui.QWidget(self.frame_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 10, 241, 121))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_2.setContentsMargins(10, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.BaudRate_lineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.BaudRate_lineEdit.setMaximumSize(QtCore.QSize(110, 20))
        self.BaudRate_lineEdit.setObjectName(_fromUtf8("BaudRate_lineEdit"))
        self.gridLayout_2.addWidget(self.BaudRate_lineEdit, 1, 1, 1, 1)
        self.Port_num_comboBox = QtGui.QComboBox(self.layoutWidget5)
        self.Port_num_comboBox.setMinimumSize(QtCore.QSize(110, 0))
        self.Port_num_comboBox.setMaximumSize(QtCore.QSize(110, 20))
        self.Port_num_comboBox.setObjectName(_fromUtf8("Port_num_comboBox"))
        self.gridLayout_2.addWidget(self.Port_num_comboBox, 0, 1, 1, 1)
        self.open_pushButton = QtGui.QPushButton(self.layoutWidget5)
        self.open_pushButton.setMinimumSize(QtCore.QSize(110, 28))
        self.open_pushButton.setMaximumSize(QtCore.QSize(110, 28))
        self.open_pushButton.setObjectName(_fromUtf8("open_pushButton"))
        self.gridLayout_2.addWidget(self.open_pushButton, 2, 0, 1, 1)
        self.stop_pushButton = QtGui.QPushButton(self.layoutWidget5)
        self.stop_pushButton.setMinimumSize(QtCore.QSize(110, 28))
        self.stop_pushButton.setMaximumSize(QtCore.QSize(110, 28))
        self.stop_pushButton.setObjectName(_fromUtf8("stop_pushButton"))
        self.gridLayout_2.addWidget(self.stop_pushButton, 2, 1, 1, 1)
        self.HOSI_IP_Label = QtGui.QLabel(self.layoutWidget5)
        self.HOSI_IP_Label.setObjectName(_fromUtf8("HOSI_IP_Label"))
        self.gridLayout_2.addWidget(self.HOSI_IP_Label, 1, 0, 1, 1)
        self.socket_type_label = QtGui.QLabel(self.layoutWidget5)
        self.socket_type_label.setObjectName(_fromUtf8("socket_type_label"))
        self.gridLayout_2.addWidget(self.socket_type_label, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_11, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame_3 = QtGui.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(-10, 0, 281, 151))
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.disconnect_pushButton = QtGui.QPushButton(self.frame_3)
        self.disconnect_pushButton.setGeometry(QtCore.QRect(160, 80, 91, 31))
        self.disconnect_pushButton.setObjectName(_fromUtf8("disconnect_pushButton"))
        self.label_27 = QtGui.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(60, 20, 54, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.connect_pushButton = QtGui.QPushButton(self.frame_3)
        self.connect_pushButton.setGeometry(QtCore.QRect(40, 80, 91, 31))
        self.connect_pushButton.setObjectName(_fromUtf8("connect_pushButton"))
        self.server_ip_lineEdit = QtGui.QLineEdit(self.frame_3)
        self.server_ip_lineEdit.setGeometry(QtCore.QRect(160, 20, 91, 20))
        self.server_ip_lineEdit.setObjectName(_fromUtf8("server_ip_lineEdit"))
        self.label_28 = QtGui.QLabel(self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(60, 50, 54, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.server_port_lineEdit = QtGui.QLineEdit(self.frame_3)
        self.server_port_lineEdit.setGeometry(QtCore.QRect(160, 50, 91, 20))
        self.server_port_lineEdit.setObjectName(_fromUtf8("server_port_lineEdit"))
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1300, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuVideo = QtGui.QMenu(self.menuBar)
        self.menuVideo.setObjectName(_fromUtf8("menuVideo"))
        self.menuOpen_Camera = QtGui.QMenu(self.menuVideo)
        self.menuOpen_Camera.setObjectName(_fromUtf8("menuOpen_Camera"))
        self.menuMonitor = QtGui.QMenu(self.menuBar)
        self.menuMonitor.setObjectName(_fromUtf8("menuMonitor"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionUpdate_uart_port = QtGui.QAction(MainWindow)
        self.actionUpdate_uart_port.setObjectName(_fromUtf8("actionUpdate_uart_port"))
        self.actionCamera1 = QtGui.QAction(MainWindow)
        self.actionCamera1.setObjectName(_fromUtf8("actionCamera1"))
        self.actionCamera2 = QtGui.QAction(MainWindow)
        self.actionCamera2.setObjectName(_fromUtf8("actionCamera2"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionOpen_Alert = QtGui.QAction(MainWindow)
        self.actionOpen_Alert.setObjectName(_fromUtf8("actionOpen_Alert"))
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionUpdate_uart_port)
        self.menuOpen_Camera.addAction(self.actionCamera1)
        self.menuOpen_Camera.addAction(self.actionCamera2)
        self.menuVideo.addAction(self.menuOpen_Camera.menuAction())
        self.menuVideo.addAction(self.actionClose)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuVideo.menuAction())
        self.menuBar.addAction(self.menuMonitor.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Port_num_comboBox, self.BaudRate_lineEdit)
        MainWindow.setTabOrder(self.BaudRate_lineEdit, self.open_pushButton)
        MainWindow.setTabOrder(self.open_pushButton, self.stop_pushButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "小虾米", None))
        self.groupBox.setTitle(_translate("MainWindow", "Display", None))
        self.label_3.setText(_translate("MainWindow", "ACC-Z:", None))
        self.label_2.setText(_translate("MainWindow", "ACC-Y:", None))
        self.label_4.setText(_translate("MainWindow", "GYO-X:", None))
        self.label_6.setText(_translate("MainWindow", "GYO-Z:", None))
        self.label_8.setText(_translate("MainWindow", "GYO-SCALE:", None))
        self.label.setText(_translate("MainWindow", "ACC-X:", None))
        self.label_5.setText(_translate("MainWindow", "GYO-Y:", None))
        self.label_7.setText(_translate("MainWindow", "ACC-SCALE:", None))
        self.acc_scale_up_Button.setText(_translate("MainWindow", "↑", None))
        self.acc_scale_down_Button.setText(_translate("MainWindow", "↓", None))
        self.gyo_scale_up_Button.setText(_translate("MainWindow", "↑", None))
        self.gyo_scale_down_Button.setText(_translate("MainWindow", "↓", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Canvas Settings", None))
        self.canvas_pause_pushButton.setText(_translate("MainWindow", "Canvas Pause", None))
        self.canvas_start_pushButton.setText(_translate("MainWindow", "Canvas Start", None))
        self.acc_groupBox.setTitle(_translate("MainWindow", "ACC", None))
        self.gyo_groupBox.setTitle(_translate("MainWindow", "GYO", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Live", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "ACC", None))
        self.label_9.setText(_translate("MainWindow", "FCHOICE_B:", None))
        self.label_10.setText(_translate("MainWindow", "DLPF_CFG:", None))
        self.label_11.setText(_translate("MainWindow", "FS_SEL:", None))
        self.label_25.setText(_translate("MainWindow", "Bandiwdth:", None))
        self.acc_bw_label.setText(_translate("MainWindow", "0", None))
        self.label_29.setText(_translate("MainWindow", "Scale:", None))
        self.acc_scale_label.setText(_translate("MainWindow", "0", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "GYO", None))
        self.label_12.setText(_translate("MainWindow", "FCHOICE_B:", None))
        self.label_13.setText(_translate("MainWindow", "DLPF_CFG:", None))
        self.label_14.setText(_translate("MainWindow", "FS_SEL:", None))
        self.label_26.setText(_translate("MainWindow", "Bandiwdth:", None))
        self.gyo_bw_label.setText(_translate("MainWindow", "0", None))
        self.label_30.setText(_translate("MainWindow", "Scale:", None))
        self.gyo_scale_label.setText(_translate("MainWindow", "0", None))
        self.read_config_pushButton.setText(_translate("MainWindow", "Read", None))
        self.write_config_pushButton.setText(_translate("MainWindow", "Write", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Gyo Configure", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "FCHOICE_B", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DLPF_CFG", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bandwidth", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1/3", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "x", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "8800", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "x", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "3600", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "250", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "184", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "92", None))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "41", None))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "20", None))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("MainWindow", "3600", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_20.setText(_translate("MainWindow", "FS_SEL:", None))
        self.label_21.setText(_translate("MainWindow", "2 = ±1000dps", None))
        self.label_22.setText(_translate("MainWindow", "1 = ±500dps", None))
        self.label_23.setText(_translate("MainWindow", "3 = ±2000dps", None))
        self.label_24.setText(_translate("MainWindow", "0 = ±250dps", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "ACC Configure", None))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "-", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "FCHOICE_B", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DLPF_CFG", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bandwidth", None))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("MainWindow", "x", None))
        item = self.tableWidget_3.item(0, 2)
        item.setText(_translate("MainWindow", "1.13 K", None))
        item = self.tableWidget_3.item(1, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_3.item(1, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_3.item(1, 2)
        item.setText(_translate("MainWindow", "460", None))
        item = self.tableWidget_3.item(2, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_3.item(2, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_3.item(2, 2)
        item.setText(_translate("MainWindow", "184", None))
        item = self.tableWidget_3.item(3, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_3.item(3, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_3.item(3, 2)
        item.setText(_translate("MainWindow", "92", None))
        item = self.tableWidget_3.item(4, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_3.item(4, 1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_3.item(4, 2)
        item.setText(_translate("MainWindow", "41", None))
        item = self.tableWidget_3.item(5, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_3.item(5, 1)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_3.item(5, 2)
        item.setText(_translate("MainWindow", "20", None))
        item = self.tableWidget_3.item(6, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_3.item(6, 1)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_3.item(6, 2)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_3.item(7, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_3.item(7, 1)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_3.item(7, 2)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_3.item(8, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_3.item(8, 1)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_3.item(8, 2)
        item.setText(_translate("MainWindow", "460", None))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_15.setText(_translate("MainWindow", "FS_SEL:", None))
        self.label_16.setText(_translate("MainWindow", "0 = ±2G", None))
        self.label_17.setText(_translate("MainWindow", "1 = ±4G", None))
        self.label_18.setText(_translate("MainWindow", "2 = ±8G", None))
        self.label_19.setText(_translate("MainWindow", "3 = ±16G", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Configure", None))
        self.status_label.setText(_translate("MainWindow", "井盖正常", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Monitor", None))
        self.recordButton.setText(_translate("MainWindow", "Force Record", None))
        self.recordButton.setShortcut(_translate("MainWindow", "Space", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Legend", None))
        self.x_legend_label.setText(_translate("MainWindow", "X:-----", None))
        self.y_legend_label.setText(_translate("MainWindow", "y:-----", None))
        self.z_legend_label.setText(_translate("MainWindow", "Z:-----", None))
        self.single_radioButton.setText(_translate("MainWindow", "Single", None))
        self.sequence_radioButton.setText(_translate("MainWindow", "Sequence", None))
        self.open_pushButton.setText(_translate("MainWindow", "UART Open", None))
        self.stop_pushButton.setText(_translate("MainWindow", "UART Stop", None))
        self.HOSI_IP_Label.setText(_translate("MainWindow", "Baud Rate", None))
        self.socket_type_label.setText(_translate("MainWindow", "Serial Port", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("MainWindow", "USART", None))
        self.disconnect_pushButton.setText(_translate("MainWindow", "Disconnect", None))
        self.label_27.setText(_translate("MainWindow", "Server IP", None))
        self.connect_pushButton.setText(_translate("MainWindow", "Connect", None))
        self.server_ip_lineEdit.setText(_translate("MainWindow", "10.10.100.254", None))
        self.label_28.setText(_translate("MainWindow", "Port", None))
        self.server_port_lineEdit.setText(_translate("MainWindow", "8899", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "WIFI", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuVideo.setTitle(_translate("MainWindow", "Camera", None))
        self.menuOpen_Camera.setTitle(_translate("MainWindow", "Open", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionUpdate_uart_port.setText(_translate("MainWindow", "Update Uart Port", None))
        self.actionUpdate_uart_port.setShortcut(_translate("MainWindow", "F5", None))
        self.actionCamera1.setText(_translate("MainWindow", "Camera1", None))
        self.actionCamera1.setShortcut(_translate("MainWindow", "F1", None))
        self.actionCamera2.setText(_translate("MainWindow", "Camera2", None))
        self.actionCamera2.setShortcut(_translate("MainWindow", "F2", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Q", None))
        self.actionOpen_Alert.setText(_translate("MainWindow", "Open Alert", None))

