# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1566, 800)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/form.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.settings_groupBox = QtGui.QGroupBox(self.centralWidget)
        self.settings_groupBox.setGeometry(QtCore.QRect(10, 10, 271, 261))
        self.settings_groupBox.setObjectName(_fromUtf8("settings_groupBox"))
        self.layoutWidget = QtGui.QWidget(self.settings_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 241, 231))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_2.setContentsMargins(10, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.HOSI_IP_Label = QtGui.QLabel(self.layoutWidget)
        self.HOSI_IP_Label.setObjectName(_fromUtf8("HOSI_IP_Label"))
        self.gridLayout_2.addWidget(self.HOSI_IP_Label, 1, 0, 1, 1)
        self.port_num_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.port_num_lineEdit.setMaximumSize(QtCore.QSize(110, 20))
        self.port_num_lineEdit.setObjectName(_fromUtf8("port_num_lineEdit"))
        self.gridLayout_2.addWidget(self.port_num_lineEdit, 2, 1, 1, 1)
        self.port_num_label = QtGui.QLabel(self.layoutWidget)
        self.port_num_label.setObjectName(_fromUtf8("port_num_label"))
        self.gridLayout_2.addWidget(self.port_num_label, 2, 0, 1, 1)
        self.HOST_IP_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.HOST_IP_lineEdit.setMaximumSize(QtCore.QSize(110, 20))
        self.HOST_IP_lineEdit.setObjectName(_fromUtf8("HOST_IP_lineEdit"))
        self.gridLayout_2.addWidget(self.HOST_IP_lineEdit, 1, 1, 1, 1)
        self.socket_type_comboBox = QtGui.QComboBox(self.layoutWidget)
        self.socket_type_comboBox.setMinimumSize(QtCore.QSize(110, 0))
        self.socket_type_comboBox.setMaximumSize(QtCore.QSize(110, 20))
        self.socket_type_comboBox.setObjectName(_fromUtf8("socket_type_comboBox"))
        self.socket_type_comboBox.addItem(_fromUtf8(""))
        self.socket_type_comboBox.addItem(_fromUtf8(""))
        self.socket_type_comboBox.addItem(_fromUtf8(""))
        self.socket_type_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.socket_type_comboBox, 0, 1, 1, 1)
        self.socket_type_label = QtGui.QLabel(self.layoutWidget)
        self.socket_type_label.setObjectName(_fromUtf8("socket_type_label"))
        self.gridLayout_2.addWidget(self.socket_type_label, 0, 0, 1, 1)
        self.record_data_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.record_data_checkBox.setObjectName(_fromUtf8("record_data_checkBox"))
        self.gridLayout_2.addWidget(self.record_data_checkBox, 3, 0, 1, 1)
        self.open_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.open_pushButton.setMinimumSize(QtCore.QSize(110, 28))
        self.open_pushButton.setMaximumSize(QtCore.QSize(110, 28))
        self.open_pushButton.setObjectName(_fromUtf8("open_pushButton"))
        self.gridLayout_2.addWidget(self.open_pushButton, 4, 0, 1, 1)
        self.open_data_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.open_data_pushButton.setMinimumSize(QtCore.QSize(110, 28))
        self.open_data_pushButton.setMaximumSize(QtCore.QSize(110, 28))
        self.open_data_pushButton.setObjectName(_fromUtf8("open_data_pushButton"))
        self.gridLayout_2.addWidget(self.open_data_pushButton, 3, 1, 1, 1)
        self.stop_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.stop_pushButton.setMinimumSize(QtCore.QSize(110, 28))
        self.stop_pushButton.setMaximumSize(QtCore.QSize(110, 28))
        self.stop_pushButton.setObjectName(_fromUtf8("stop_pushButton"))
        self.gridLayout_2.addWidget(self.stop_pushButton, 4, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 380, 271, 231))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(12, 32, 231, 199))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.acc_x_Label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.acc_x_Label.setFont(font)
        self.acc_x_Label.setText(_fromUtf8(""))
        self.acc_x_Label.setObjectName(_fromUtf8("acc_x_Label"))
        self.gridLayout.addWidget(self.acc_x_Label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.acc_y_Label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.acc_y_Label.setFont(font)
        self.acc_y_Label.setText(_fromUtf8(""))
        self.acc_y_Label.setObjectName(_fromUtf8("acc_y_Label"))
        self.gridLayout.addWidget(self.acc_y_Label, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.acc_z_Label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.acc_z_Label.setFont(font)
        self.acc_z_Label.setText(_fromUtf8(""))
        self.acc_z_Label.setObjectName(_fromUtf8("acc_z_Label"))
        self.gridLayout.addWidget(self.acc_z_Label, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.gyo_x_Label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.gyo_x_Label.setFont(font)
        self.gyo_x_Label.setText(_fromUtf8(""))
        self.gyo_x_Label.setObjectName(_fromUtf8("gyo_x_Label"))
        self.gridLayout.addWidget(self.gyo_x_Label, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.gyo_y_Label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.gyo_y_Label.setFont(font)
        self.gyo_y_Label.setText(_fromUtf8(""))
        self.gyo_y_Label.setObjectName(_fromUtf8("gyo_y_Label"))
        self.gridLayout.addWidget(self.gyo_y_Label, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.gyo_z_Label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setItalic(False)
        self.gyo_z_Label.setFont(font)
        self.gyo_z_Label.setText(_fromUtf8(""))
        self.gyo_z_Label.setObjectName(_fromUtf8("gyo_z_Label"))
        self.gridLayout.addWidget(self.gyo_z_Label, 5, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 20, 1251, 346))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(300, 380, 1251, 346))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 270, 271, 111))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 236, 81))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_3.setContentsMargins(10, 11, 11, 11)
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalSlider = QtGui.QSlider(self.layoutWidget2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout_3.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.canvas_start_pushButton = QtGui.QPushButton(self.layoutWidget2)
        self.canvas_start_pushButton.setMinimumSize(QtCore.QSize(110, 28))
        self.canvas_start_pushButton.setMaximumSize(QtCore.QSize(110, 28))
        self.canvas_start_pushButton.setObjectName(_fromUtf8("canvas_start_pushButton"))
        self.gridLayout_3.addWidget(self.canvas_start_pushButton, 1, 0, 1, 1)
        self.canvas_pause_pushButton = QtGui.QPushButton(self.layoutWidget2)
        self.canvas_pause_pushButton.setMinimumSize(QtCore.QSize(110, 28))
        self.canvas_pause_pushButton.setMaximumSize(QtCore.QSize(110, 28))
        self.canvas_pause_pushButton.setObjectName(_fromUtf8("canvas_pause_pushButton"))
        self.gridLayout_3.addWidget(self.canvas_pause_pushButton, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1566, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.socket_type_comboBox, self.HOST_IP_lineEdit)
        MainWindow.setTabOrder(self.HOST_IP_lineEdit, self.port_num_lineEdit)
        MainWindow.setTabOrder(self.port_num_lineEdit, self.record_data_checkBox)
        MainWindow.setTabOrder(self.record_data_checkBox, self.open_data_pushButton)
        MainWindow.setTabOrder(self.open_data_pushButton, self.open_pushButton)
        MainWindow.setTabOrder(self.open_pushButton, self.stop_pushButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Ð¡ÏºÃ×", None))
        self.settings_groupBox.setTitle(_translate("MainWindow", "Socket Settings", None))
        self.HOSI_IP_Label.setText(_translate("MainWindow", "HOST IP:", None))
        self.port_num_label.setText(_translate("MainWindow", "Port Num:", None))
        self.socket_type_comboBox.setItemText(0, _translate("MainWindow", "TCP/Client", None))
        self.socket_type_comboBox.setItemText(1, _translate("MainWindow", "TCP/Server", None))
        self.socket_type_comboBox.setItemText(2, _translate("MainWindow", "UDP/Client", None))
        self.socket_type_comboBox.setItemText(3, _translate("MainWindow", "UDP/Server", None))
        self.socket_type_label.setText(_translate("MainWindow", "Socket Type:", None))
        self.record_data_checkBox.setText(_translate("MainWindow", "Record Data", None))
        self.open_pushButton.setText(_translate("MainWindow", "Socket Open", None))
        self.open_data_pushButton.setText(_translate("MainWindow", "Open Data", None))
        self.stop_pushButton.setText(_translate("MainWindow", "Socket Stop", None))
        self.groupBox.setTitle(_translate("MainWindow", "Display", None))
        self.label.setText(_translate("MainWindow", "ACC-X:", None))
        self.label_2.setText(_translate("MainWindow", "ACC-Y:", None))
        self.label_3.setText(_translate("MainWindow", "ACC-Z:", None))
        self.label_4.setText(_translate("MainWindow", "GYO-X:", None))
        self.label_5.setText(_translate("MainWindow", "GYO-Y:", None))
        self.label_6.setText(_translate("MainWindow", "GYO-Z:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "ACC", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "GYO", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Canvas Settings", None))
        self.label_7.setText(_translate("MainWindow", "Scale:", None))
        self.canvas_start_pushButton.setText(_translate("MainWindow", "Canvas Start", None))
        self.canvas_pause_pushButton.setText(_translate("MainWindow", "Canvas Pause", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

